# Project 1 - RL For Atari Breakout Game
Train a Reinforcement Learning agent to play Atari games.
- https://www.gymlibrary.dev/environments/atari/

## 1. Import Dependencies

In [1]:
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack   # train on more than one env a time
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os

## 2. Test Environment

In [2]:
# Download this file here - http://www.atarimania.com/roms/Roms.rar

In [3]:
environment_name = "Breakout-v0"
env = gym.make(environment_name)
env.reset()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [4]:
env.action_space,env.observation_space

(Discrete(4),
 Box([[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]
 
  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]
 
  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]
 
  ...
 
  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]
 
  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]
 
  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]], [[[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]
 
  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]
 
  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]
 
  ...
 
  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [255 255 255]
   [255 255 255]
   [255 255 255]]
 
  [[255 255 255]
   [255 255 255]
   [255 255 255]
   ...
   [2

In [5]:
episodes = 5  # think of it as one episode of full game
for episode in range(1,episodes+1):
    obs = env.reset()  # reset the agent , action , environment , obsevation , rewards
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()  # return random value between (0,1)
        obs,reward , done,info = env.step(action)
        score += reward
        
        # print(f"Action: {action} ,Score: {score} >> Other Infos: n_state {n_state},Reward {reward},Done {done}")
    print(f'Episode: {episode}, Score:{score}')

d:\Src\Anaconda\lib\site-packages\gym\envs\atari\environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(
d:\Src\Anaconda\lib\site-packages\pyglet\image\codecs\wic.py:406: UserWarning: [WinError -2147417850] Cannot change thread mode after it is set
  warnings.warn(str(err))


Episode: 1, Score:2.0
Episode: 2, Score:4.0
Episode: 3, Score:1.0
Episode: 4, Score:1.0
Episode: 5, Score:6.0
Episode: 6, Score:2.0
Episode: 7, Score:1.0
Episode: 8, Score:1.0
Episode: 9, Score:3.0
Episode: 10, Score:1.0
Episode: 11, Score:1.0
Episode: 12, Score:4.0
Episode: 13, Score:3.0
Episode: 14, Score:1.0
Episode: 15, Score:5.0
Episode: 16, Score:1.0
Episode: 17, Score:8.0
Episode: 18, Score:3.0
Episode: 19, Score:2.0
Episode: 20, Score:3.0
Episode: 21, Score:8.0
Episode: 22, Score:2.0
Episode: 23, Score:1.0
Episode: 24, Score:0.0
Episode: 25, Score:9.0
Episode: 26, Score:0.0
Episode: 27, Score:3.0
Episode: 28, Score:1.0
Episode: 29, Score:3.0
Episode: 30, Score:0.0
Episode: 31, Score:0.0
Episode: 32, Score:0.0
Episode: 33, Score:1.0
Episode: 34, Score:2.0
Episode: 35, Score:1.0
Episode: 36, Score:2.0
Episode: 37, Score:3.0
Episode: 38, Score:1.0
Episode: 39, Score:1.0
Episode: 40, Score:1.0
Episode: 41, Score:2.0
Episode: 42, Score:0.0
Episode: 43, Score:3.0
Episode: 44, Score:3

In [6]:
env.close()

## 3. Vectorise Environment and Train Model
Train more than one Environment at the same time

In [7]:
env = make_atari_env('Breakout-v0' , n_envs= 4 ,seed = 0)
env = VecFrameStack(env,n_stack = 4)
env.reset()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [8]:
env.render()

In [9]:
# Creating the model to start Training
log_path = os.path.join("Training","Logs")
model = A2C('CnnPolicy', env , verbose = 1,tensorboard_log = log_path)

Using cuda device
Wrapping the env in a VecTransposeImage.


In [10]:
# Training 
model.learn(total_timesteps = 100)

Logging to Training\Logs\A2C_1


## 4. Save and Reload Model

In [11]:
# Saving the model
a2c_path = os.path.join("Training","Saved Models","A2C_Breakout_Model")
model.save(a2c_path)

In [12]:
# Reloading the model
del model

In [13]:
model = A2C.load(a2c_path,env)

Wrapping the env in a VecTransposeImage.


# 5. Evaluete and Test

In [17]:
env = make_atari_env('Breakout-v0' , n_envs= 1 ,seed = 0 )
env = VecFrameStack(env,n_stack = 4)

In [18]:
evaluate_policy(model,env,n_eval_episodes=10,render=True)

d:\Src\Anaconda\lib\site-packages\gym\envs\atari\environment.py:267: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(


(1.2, 0.8717797887081347)

: 

> Just train the model for longer and you will get much better Performance 